config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "tasks/new", to: 'tasks#new', as: 'new_task'
  get "/tasks", to: "tasks#index"
  get "/tasks/:id", to: "tasks#show", as: 'task'
  post "/tasks", to: "tasks#create"
  get "/tasks/:id/edit", to: "tasks#edit", as: 'edit_task'
  patch '/tasks/:id', to:"tasks#update"
  delete '/tasks/:id', to:"tasks#destroy", as: 'destroy_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with model: @task do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "update Task", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Back to tasks', tasks_path, class: 'btn btn-secondary' %>

app/views/tasks/index.html.erb
<h1><strong>My Tasks</strong></h1>

<ul class="list-unstyled">
  <% @tasks.each do |task|  %>
    <li class="d-flex align-items-center">
      <%= check_box_tag "task_#{task.id}", task.id %>
      <%= link_to task.title, task_path(task) %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add New Task', new_task_path, class: 'btn btn-success mb-3' %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :details %>
    <%= form.text_area :details, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Create Task", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Back to tasks', tasks_path, class: 'btn btn-secondary' %>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>
<p><%= @task.details %></p>

<%= link_to 'Back to list', tasks_path %>
<%= link_to 'Edit Task', edit_task_path(@task), class: 'btn btn-success mb-3' %>
<%= link_to 'delete Task', destroy_task_path(@task), class: 'btn btn-success mb-3', data: { turbo_method: :delete, turbo_confirm: "Vous êtes-sûr ?" } %>